AnitsukiTV/Controllers/LanetlerKralıAdminController.cs
using AnitsukiTV.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Xml.Linq;
using PagedList;
using PagedList.Mvc;
using System.Web.UI.WebControls;
using System.Web.Services.Description;
using System.Data.Entity;

namespace AnitsukiTV.Controllers
{
    [Authorize]
    public class LanetlerKralıAdminController : Controller
    {
        AnitsukiTVEntities db = new AnitsukiTVEntities();
        TabeList veri = new TabeList();
        // GET: LanetlerKralıAdmin
        public ActionResult Index()
        {
            veri.Anime = db.TBLANIME.ToList();
            veri.Episode = db.TBLEPISODE.ToList();
            veri.Users = db.TBLUSER.ToList();
            ViewBag.animecount = veri.Anime.Count(x=>x.STATUS == true);
            ViewBag.episodecount = veri.Episode.Count(x=>x.STATUS == true);
            ViewBag.usercounttrue = db.TBLUSER.Count(x=>x.STATUS == true);
            ViewBag.usercountfalse = db.TBLUSER.Count(x => x.STATUS == false);
            return View(veri);
        }
        public ActionResult Message()
        {
            var degerler = db.TBLNOTIFICATIONS.Where(x => x.ADMINSTATUS == true).OrderByDescending(x => x.ID).ToList();
            return View(degerler);
        }

        [HttpPost]
        public JsonResult ClearAllNotifications()
        {
            var messages = db.TBLNOTIFICATIONS.Where(n => n.ADMINSTATUS == true).ToList();
            foreach (var message in messages)
            {
                message.ADMINSTATUS = false;
                message.ISCLEARED = true;
            }
            db.SaveChanges();
            return Json(new { success = true, message = "Tüm bildirimler temizlendi." });
        }

        public ActionResult Admin()
        {
            var degerler = db.TBLADMIN.ToList();
            return View(degerler);
        }

        public ActionResult Status()
        {
            var degerler = db.TBLADMIN.Where(x => x.STATUS == false).OrderByDescending(x => x.ID).ToList();
            return View(degerler);
        }

        [HttpGet]
        public ActionResult AddAdmin()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddAdmin(TBLADMIN add)
        {
            try
            {
                TBLADMIN admin = new TBLADMIN();
                admin.USERNAME = add.USERNAME;
                admin.PASSWORD = add.PASSWORD;
                admin.ADMINROLEID = add.ADMINROLEID;
                admin.DATE = Convert.ToDateTime(DateTime.Now.ToShortDateString());
                admin.STATUS = true;

                db.TBLADMIN.Add(admin);
                db.SaveChanges();

                TempData["success"] = "Admin başarıyla eklendi";
                return RedirectToAction("Admin");
            }
            catch (Exception ex)
            {
                TempData["error"] = "Admin eklenirken bir hata oluştu: " + ex.Message;
                return RedirectToAction("Admin");
            }
        }

        public ActionResult UpdateAdmin(int id)
        {
            var FindAdmin = db.TBLADMIN.Find(id);
            return View("UpdateAdmin", FindAdmin);
        }

        public ActionResult AdminSave(TBLADMIN admin)
        {
            try
            {
                var updateadmin = db.TBLADMIN.Find(admin.ID);
                updateadmin.USERNAME = admin.USERNAME;
                updateadmin.PASSWORD = admin.PASSWORD;
                updateadmin.ADMINROLEID = admin.ADMINROLEID;

                db.SaveChanges();
                TempData["success1"] = "Admin başarıyla güncellendi";
                return RedirectToAction("Admin");
            }
            catch (Exception ex)
            {
                TempData["error1"] = "Admin güncellenirken bir hata oluştu: " + ex.Message;
                return RedirectToAction("Admin");
            }
        }

        [HttpPost]
        public ActionResult ActivePassive(int id)
        {
            var AdminActivePassive = db.TBLADMIN.Find(id);
            if (AdminActivePassive == null)
            {
                return Json(new { success = false });
            }
            AdminActivePassive.STATUS = !AdminActivePassive.STATUS; 
            db.SaveChanges();

            return Json(new { status = AdminActivePassive.STATUS });
        }

        public ActionResult Delete(int id)
        {
            try
            {
                var AdminFind = db.TBLADMIN.Find(id);
                db.TBLADMIN.Remove(AdminFind);
                db.SaveChanges();
                TempData["success2"] = "Admin başarıyla silindi";
            }
            catch (Exception ex)
            {
                TempData["error2"] = "Admin silinirken bir hata oluştu: " + ex.Message;
            }

            return RedirectToAction("Admin");
        }


        public ActionResult AdminRole()
        {
            var degerler = db.TBLADMINROLE.ToList();
            return View(degerler);
        }

        [HttpGet]
        public ActionResult AddRole()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddRole(TBLADMINROLE add)
        {
            try
            {
                TBLADMINROLE admin = new TBLADMINROLE();
                admin.ROLENAME = add.ROLENAME;

                db.TBLADMINROLE.Add(admin);
                db.SaveChanges();
                TempData["success"] = "Rol başarıyla eklendi.";
                return RedirectToAction("AdminRole");
            }
            catch (Exception ex)
            {
                TempData["error"] = "Rol eklenirken bir hata oluştu: " + ex.Message;
                return RedirectToAction("AdminRole");
            }
        }


        public ActionResult UpdateRole(int id)
        {
            var FindRole = db.TBLADMINROLE.Find(id);
            return View("UpdateRole", FindRole);
        }


        public ActionResult RoleSave(TBLADMINROLE role)
        {
            try
            {
                var updaterole = db.TBLADMINROLE.Find(role.ID);
                updaterole.ROLENAME = role.ROLENAME;
                db.SaveChanges();
                TempData["success1"] = "Rol başarıyla güncellendi.";
            }
            catch (Exception ex)
            {
                TempData["error1"] = "Rol güncellenirken bir hata oluştu: " + ex.Message;
            }
            return RedirectToAction("AdminRole");
        }



        public ActionResult Category()
        {
            var degerler = db.TBLCATEGORY.ToList();
            return View(degerler);
        }

        public ActionResult CategoryStatus()
        {
            var degerler = db.TBLCATEGORY.Where(x => x.STATUS == false).OrderByDescending(x=>x.ID).ToList();
            return View(degerler);
        }


        [HttpGet]
        public ActionResult AddCategory()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddCategory(TBLCATEGORY add)
        {
            try
            {
                TBLCATEGORY category = new TBLCATEGORY();
                category.CATEGORYNAME = add.CATEGORYNAME;
                category.STATUS = true;
                db.TBLCATEGORY.Add(category);
                db.SaveChanges();
                TempData["success"] = "Kategori başarıyla eklendi.";
            }
            catch (Exception ex)
            {
                TempData["error"] = "Kategori eklenirken bir hata oluştu: " + ex.Message;
            }
            return RedirectToAction("Category");
        }


        public ActionResult UpdateCategory(int id)
        {
            var FindCategory = db.TBLCATEGORY.Find(id);
            return View("UpdateCategory", FindCategory);
        }

        public ActionResult CategorySave(TBLCATEGORY cat)
        {
            try
            {
                var updatecategory = db.TBLCATEGORY.Find(cat.ID);
                updatecategory.CATEGORYNAME = cat.CATEGORYNAME;
                db.SaveChanges();
                TempData["success1"] = "Kategori başarıyla güncellendi.";
            }
            catch (Exception ex)
            {
                TempData["error1"] = "Kategori güncellenirken bir hata oluştu: " + ex.Message;
            }
            
            return RedirectToAction("Category");
        }

        [HttpPost]
        public ActionResult ActivePassive8(int id)
        {
            var AdminActivePassive8 = db.TBLCATEGORY.Find(id);
            if (AdminActivePassive8 == null)
            {
                return Json(new { success = false });
            }
            AdminActivePassive8.STATUS = !AdminActivePassive8.STATUS;
            db.SaveChanges();

            return Json(new { status = AdminActivePassive8.STATUS });
        }



        public ActionResult Anime(string anime, int p = 1)
        {
            var degerler = from a in db.TBLANIME select a;
            if (!string.IsNullOrEmpty(anime))
            {
                degerler = degerler.Where(x => x.ANIMENAME.ToLower().Contains(anime.ToLower()));
            }
            var pageSize = 50;
            var paginatedResults = degerler.OrderByDescending(x => x.ID).Skip((p - 1) * pageSize).Take(pageSize).ToList();
            var pagedList = new StaticPagedList<TBLANIME>(paginatedResults, p, pageSize, degerler.Count());
            ViewBag.PageCount = (int)Math.Ceiling(degerler.Count() / (double)pageSize);
            ViewBag.CurrentPage = p;
            ViewBag.Anime = anime; 
            return View(pagedList);
        }

        public ActionResult AnimeStatus()
        {
            var degerler = db.TBLANIME.Where(x => x.STATUS == false).OrderByDescending(x=>x.ID).ToList();
            return View(degerler);
        }

        public ActionResult AnimeAdminStatus()
        {

AnitsukiTV/Views/LanetlerKralıAdmin/AddEpisode.cshtml
@model AnitsukiTV.Models.TBLEPISODE

@{
    ViewBag.Title = "AddEpisode";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<style>
    #anime-search {
        width: 100%;
        padding: 5px;
        border: 1px solid #ccc;
        border-radius: 5px;
        margin-bottom: 10px;
    }

    #anime-dropdown {
        width: 100%;
        padding: 5px;
        border: 1px solid #000000;
        border-radius: 5px;
    }

        #anime-dropdown option {
            display: block;
        }

    #season-dropdown {
        width: 100%;
        padding: 5px;
        border: 1px solid #000000;
        border-radius: 5px;
    }
</style>


<script src="~/Scripts/jquery-3.7.0.slim.min.js"></script>

@using (Html.BeginForm("AddEpisode", "LanetlerKralıAdmin", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    <form class="forms-sample">
        <div style="width:100%; height:auto; display:flex;align-items:center; justify-content:space-around;" class="form-group">
            <div>
                <div style="margin-bottom:10px;">
                    <label for="exampleInputPassword4">Video URL</label>
                    <br />
                    <video controls class="Video2" width="400" height="250" style="border:1px solid #000000; object-fit:cover;" id="videoPlayerr"></video>
                    <div class="d-flex">
                        @Html.TextBoxFor(x => x.EP2, new { @class = "form-control", @placeholder = ".MP4 uzantılı linkleri giriniz buraya", @style = "width:100%; border:1px solid #000000; padding:3px;", @id = "videoUrlInputt" })
                        <button class="btn btn-primary" type="button" id="previewButtonn">Önizle</button>
                    </div>
                </div>

                <div>
                    <label for="exampleInputPassword4">720</label>
                    <br />
                    <video controls class="Video3" width="400" height="250" style="border:1px solid #000000; object-fit:cover;"></video>
                    <input class="form-control" id="resim" accept=".mp4" type="file" onchange="$('.Video3')[0].src = window.URL.createObjectURL(this.files[0])" name="Video3" />
                </div>
            </div>
            <div>
                <div style="margin-bottom:10px;">
                    <label for="videoUrlInput">Video IFRAME</label>
                    <br />
                    <iframe id="videoIframe" width="400" height="250" style="border:1px solid #000000; display:block;" frameborder="0" allowfullscreen></iframe>
                    <video controls id="otherVideo" width="400" height="250" style="border:1px solid #000000; display:none; object-fit:cover;"></video>
                    <div class="d-flex">
                        @Html.TextBoxFor(x => x.URL, new { @class = "form-control", @id = "videoUrlInput", @placeholder = "YouTube veya Google Drive video URL'sini buraya yapıştırın", @style = "width:100%; border:1px solid #000000; padding:3px;" })
                        <button class="btn btn-primary" type="button" id="previewButton">Önizle</button>
                    </div>
                </div>
                <div>
                    <label for="exampleInputPassword4">1080</label>
                    <br />
                    <video controls class="Video4" width="400" height="250" style="border:1px solid #000000; object-fit:cover;"></video>
                    <input class="form-control" id="resim" accept=".mp4" type="file" onchange="$('.Video4')[0].src = window.URL.createObjectURL(this.files[0])" name="Video4" />
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="exampleInputPassword4">Anime Adı</label><br />
            <input type="text" id="anime-search" placeholder="Anime Ara">
            <select id="anime-dropdown" name="ANIMEID" required onchange="getSeasonsByAnimeId(this.value)">
                <option value="">Anime Seçiniz</option>
                @foreach (var anime in ViewBag.Anime)
                {
                    <option value="@anime.ID">@anime.ANIMENAME</option>
                }
            </select>
        </div>
        <div class="form-group">
            <label for="season-dropdown">Sezon ID</label><br />
            <select id="season-dropdown" name="SEASONID" required>
                <option value="">Sezon Seçin</option>
            </select>
        </div>
        <div class="form-group">
            <label for="exampleInputPassword4">Bölüm Numarası</label><br />
            @Html.TextBoxFor(x => x.EPINUMBER, new { @style = "width:100%; border:1px solid #000000;padding:3px;", @required = "@required" })
        </div>
        <div class="form-group">
            <label for="exampleInputName1">Bölüm Adı</label><br />
            @Html.TextBoxFor(x => x.EPISODENAME, new { @style = "width:100%; border:1px solid #000000;padding:3px;", @required = "@required" })
        </div>
        <div class="form-group">
            <label for="exampleInputName1">Süre</label><br />
            @Html.TextBoxFor(x => x.TIME, new { @style = "width:100%; border:1px solid #000000;padding:3px;", @required = "@required" })
        </div>
        <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
        <a style="color:#ffffff;" class="btn btn-light" href="/LanetlerKralıAdmin/Episode">Vazgeç</a>
    </form>

}

<script>
    document.addEventListener("DOMContentLoaded", function () {
        var animeList = document.getElementById("anime-dropdown");
        var searchInput = document.getElementById("anime-search");

        searchInput.addEventListener("input", function () {
            var searchTerm = searchInput.value.toLowerCase();
            for (var i = 0; i < animeList.options.length; i++) {
                var option = animeList.options[i];
                var optionText = option.text.toLowerCase();
                if (optionText.indexOf(searchTerm) === -1) {
                    option.style.display = "none";
                } else {
                    option.style.display = "block";
                }
            }
        });
    });
</script>


<script>
    document.getElementById('previewButton').addEventListener('click', function () {
        var videoUrl = document.getElementById('videoUrlInput').value;
        var videoIframe = document.getElementById('videoIframe');
        var otherVideo = document.getElementById('otherVideo');

        if (videoUrl) {
            // YouTube URL kontrolü
            if (videoUrl.includes('youtube.com/watch?v=')) {
                var videoId = videoUrl.split('v=')[1];
                if (videoId) {
                    var ampersandPosition = videoId.indexOf('&');
                    if (ampersandPosition !== -1) {
                        videoId = videoId.substring(0, ampersandPosition);
                    }
                    videoIframe.src = "https://www.youtube.com/embed/" + videoId;
                    videoIframe.style.display = "block";
                    otherVideo.style.display = "none";
                }
            }
            // Google Drive URL kontrolü
            else if (videoUrl.includes('drive.google.com/file/d/')) {
                var fileId = videoUrl.split('/d/')[1].split('/')[0];
                videoIframe.src = "https://drive.google.com/file/d/" + fileId + "/preview";
                videoIframe.style.display = "block";
                otherVideo.style.display = "none";
            }
            // Mail.ru URL kontrolü
            else if (videoUrl.includes('mail.ru/video/embed/')) {
                videoIframe.src = videoUrl; // Doğrudan kullan
                videoIframe.style.display = "block";
                otherVideo.style.display = "none";
            }
            // Ok.ru URL kontrolü
            else if (videoUrl.includes('ok.ru/video/')) {
                var videoId = videoUrl.split('video/')[1];
                videoIframe.src = "https://ok.ru/videoembed/" + videoId; // Embed formatına dönüştür
                videoIframe.style.display = "block";
                otherVideo.style.display = "none";
            }
            // Sibnet URL kontrolü
            else if (videoUrl.includes('video.sibnet.ru/shell.php?videoid=')) {
                // Sibnet URL'sini doğrudan kullan
                videoIframe.src = videoUrl; // Doğrudan URL'yi kullan
                videoIframe.style.display = "block";
                otherVideo.style.display = "none";
            }
            else {
                alert('Lütfen geçerli bir video URL\'si girin.');
            }
        }
        else {
            alert('Lütfen geçerli bir video URL\'si girin.');
        }
    });
</script>

<script>
    function getSeasonsByAnimeId(animeId) {
        // Sezon dropdown'unu temizle
        var seasonDropdown = document.getElementById("season-dropdown");
        seasonDropdown.innerHTML = '<option value="">Sezon Seçin</option>'; // İlk seçenek

        // Eğer animeId yoksa çık
        if (!animeId) return;

        // AJAX çağrısı yap
        fetch('/LanetlerKralıAdmin/GetSeasonsByAnimeId?animeId=' + animeId)
            .then(response => response.json())
            .then(data => {
                data.forEach(function (season) {
                    var option = document.createElement("option");
                    option.value = season.ID; // SEASONID
                    option.text = season.SEASONNAME ? season.SEASONNAME : season.SEASONNUMBER; // SEASONNAME yoksa SEASONNUMBER göster
                    seasonDropdown.appendChild(option);
                });
            })
            .catch(error => console.error('Hata:', error));
    }

    document.addEventListener("DOMContentLoaded", function () {
        var animeList = document.getElementById("anime-dropdown");
        var searchInput = document.getElementById("anime-search");

        searchInput.addEventListener("input", function () {
            var searchTerm = searchInput.value.toLowerCase();
            for (var i = 0; i < animeList.options.length; i++) {
                var option = animeList.options[i];
                var optionText = option.text.toLowerCase();
                if (optionText.indexOf(searchTerm) === -1) {
                    option.style.display = "none";
                } else {
                    option.style.display = "block";
                }
            }
        });
    });
</script>

<script>
    document.getElementById('previewButtonn').addEventListener('click', function () {
        var videoUrl = document.getElementById('videoUrlInputt').value;
        var videoPlayer = document.getElementById('videoPlayerr');

        // Video URL'sini kontrol et ve videoyu yükle
        if (videoUrl.includes('.mp4')) {
            // URL içinde .mp4 var mı kontrolü yapıyoruz
            videoPlayer.src = videoUrl;
            videoPlayer.load(); // Yeni kaynağı yükle
        } else {
            alert('Lütfen geçerli bir MP4 uzantılı link girin.');
        }
    });
</script>

AnitsukiTV/Views/LanetlerKralıAdmin/AddFanSub.cshtml
@model AnitsukiTV.Models.TBLFANSUB
@{
    ViewBag.Title = "AddFanSub";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("AddCategory", "LanetlerKralıAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <form class="forms-sample">
        <div class="form-group">
            <label for="exampleInputName1">Kategori</label>
            @Html.TextBoxFor(x => x.CATEGORYNAME, new { @style = "width:100%; border:1px solid #000000;" })
        </div>
        <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
        <a style="color:#ffffff;" href="/LanetlerKralıAdmin/Category" class="btn btn-light">Vazgeç</a>
    </form>
}

AnitsukiTV/Views/LanetlerKralıAdmin/AddRole.cshtml
@model  AnitsukiTV.Models.TBLADMINROLE
@{
    ViewBag.Title = "AddRole";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@using (Html.BeginForm("AddRole", "LanetlerKralıAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <form class="forms-sample">
        <div class="form-group">
            <label for="exampleInputName1">Role Adı</label>
            @Html.TextBoxFor(x => x.ROLENAME, new { @style = "width:100%; border:1px solid #000000;" })
        </div>
        <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
        <a style="color:#000000;" href="/LanetlerKralıAdmin/AdminRole" class="btn btn bg-light">Vazgeç</a>
    </form>
}

AnitsukiTV/Views/LanetlerKralıAdmin/AddSeason.cshtml
@model AnitsukiTV.Models.TBLSEASON
@{
    ViewBag.Title = "AddSeason";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<style>
    #anime-search {
        width: 100%;
        padding: 5px;
        border: 1px solid #ccc;
        border-radius: 5px;
        margin-bottom: 10px;
    }

    #anime-dropdown {
        width: 100%;
        padding: 5px;
        border: 1px solid #000000;
        border-radius: 5px;
    }

        #anime-dropdown option {
            display: block;
        }
</style>

@using (Html.BeginForm("AddSeason", "LanetlerKralıAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <form class="forms-sample">
        <div style="width:100%; display:flex;justify-content:center;">
            <div>
                <label>Resim Yükleme</label>
                <br />
                <img class="resim" width="400" height="250" style="margin-bottom:10px;border:1px solid #000000;object-fit:cover;" />
                <input class="form-control" id="resim" accept=".avif" type="file" onchange="$('.resim')[0].src = window.URL.createObjectURL(this.files[0])" name="Image" />
            </div>
        </div>
        <div class="form-group">
            <label for="exampleInputPassword4">Anime Adı</label><br />
            <input type="text" id="anime-search" placeholder="Anime Ara">
            <select id="anime-dropdown" name="ANIMEID" required>
                <option value="" disabled selected>Anime Seç</option>
                @foreach (var anime in ViewBag.Anime)
                {
                    <option value="@anime.ID" @(ViewBag.SelectedAnimeId == anime.ID ? "selected" : "")>@anime.ANIMENAME</option>
                }
            </select>
        </div>
        <div class="form-group">
            <label for="exampleInputName1">Sezon Sayısı</label>
            @Html.TextBoxFor(x => x.SEASONNUMBER, new { @style = "width:100%; border:1px solid #000000;", @required = "required" })
        </div>
        <div class="form-group">
            <label for="exampleInputName1">Sezon Adı</label>
            @Html.TextBoxFor(x => x.SEASONNAME, new { @style = "width:100%; border:1px solid #000000;" })
        </div>
        <div class="form-group">
            <label for="exampleInputName1">FanSub</label><br />
            @Html.TextBoxFor(x => x.FANSUBAD, new { @style = "width:100%; border:1px solid #000000;padding:3px;", @required = "@required" })
        </div>
        <div class="form-group">
            <label for="exampleInputName1">Çevirici</label><br />
            @Html.TextBoxFor(x => x.TRANSLATES, new { @style = "width:100%; border:1px solid #000000;padding:3px;", @required = "@required" })
        </div>
        <div class="form-group">
            <label for="exampleInputName1">Website</label><br />
            @Html.TextBoxFor(x => x.WEBSITE, new { @style = "width:100%; border:1px solid #000000;padding:3px;", @required = "@required" })
        </div>
        <div class="form-group">
            <label for="exampleInputName1">Discord</label><br />
            @Html.TextBoxFor(x => x.DISCORD, new { @style = "width:100%; border:1px solid #000000;padding:3px;", @required = "@required" })
        </div>
        <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
        <a style="color:#ffffff;" href="/LanetlerKralıAdmin/Season" class="btn btn-light">Vazgeç</a>
    </form>
}


<script>
    document.addEventListener("DOMContentLoaded", function () {
        var animeList = document.getElementById("anime-dropdown");
        var searchInput = document.getElementById("anime-search");

        searchInput.addEventListener("input", function () {
            var searchTerm = searchInput.value.toLowerCase();
            for (var i = 0; i < animeList.options.length; i++) {
                var option = animeList.options[i];
                var optionText = option.text.toLowerCase();
                if (optionText.indexOf(searchTerm) === -1) {
                    option.style.display = "none";
                } else {
                    option.style.display = "block";
                }
            }
        });
    });
</script>

AnitsukiTV/Views/LanetlerKralıAdmin/UpdateAnime.cshtml
@model AnitsukiTV.Models.TBLANIME
@{
    ViewBag.Title = "UpdateAnime";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<script src="~/Scripts/jquery-3.7.0.slim.min.js"></script>


@using (Html.BeginForm("AnimeSave", "LanetlerKralıAdmin", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    <div class="form-group">
        <label for="exampleInputName1">ID</label>
        @Html.TextBoxFor(x => x.ID, new { @style = "width:100%; border:1px solid #000000;", @readonly = "readonly" })
    </div>
    <div style="width:100%; height:auto; display:flex; align-items:center;justify-content:space-around;" class="form-group">
        <div>
            <label>Resim Yükleme</label>
            <br />
            <img class="resim" width="250" height="400" style="margin-bottom:10px;border:1px solid #000000;object-fit:cover;" src="~/IMG/@Model.BANNER" />
            <input class="form-control" id="resim" accept=".avif" type="file" onchange="$('.resim')[0].src = window.URL.createObjectURL(this.files[0])" name="Image" />
        </div>
        <div>
            <label for="exampleInputPassword4">Büyük Banner</label><br />
            <img class="banner" width="400" height="250" style="margin-bottom:10px;border:1px solid #000000;object-fit:cover;" src="~/IMG/@Model.BIGBANNER" />
            <input class="form-control" id="resim" accept=".avif" type="file" onchange="$('.banner')[0].src = window.URL.createObjectURL(this.files[0])" name="Banner" />
        </div>
        <div>
            <label for="exampleInputPassword4">Edit</label><br />
            <video style="width:250px; height:400px; object-fit:cover;" controls class="video" src="~/Videos/@Model.EDIT"></video>
            <input type="file" id="resim" accept=".mp4" class=" form-control" onchange="$('.video')[0].src = window.URL.createObjectURL(this.files[0])" name="Video" />
        </div>
    </div>
    <div class="form-group">
        <label for="exampleInputPassword4">Kategori</label><br />
        @Html.DropDownListFor(x => x.CATEGORYID, new SelectList(ViewBag.Categories, "ID", "CATEGORYNAME", Model.CATEGORYID), new { @style = "width:100%; border:1px solid #000000;padding:3px;", @required = "@required" })
    </div>
    <div class="form-group">
        <label for="exampleInputPassword4">Tür</label><br />
        @Html.TextBoxFor(x => x.TYPE, new { @style = "width:100%; border:1px solid #000000;padding:3px;" })
    </div>
    <div class="form-group">
        <label for="exampleInputName1">Anime Adı</label><br />
        @Html.TextBoxFor(x => x.ANIMENAME, new { @style = "width:100%; border:1px solid #000000;padding:3px;" })
    </div>
    <div class="form-group">
        <label for="exampleInputName1">IMDb => Nokta kullanınız örnek(8.9)</label><br />
        @Html.TextBoxFor(x => x.IMDB, new { @style = "width:100%; border:1px solid #000000;padding:3px;" })
    </div>
    <div class="form-group">
        <label for="exampleInputName1">My Anime List => Nokta kullanınız örnek(8.9)</label><br />
        @Html.TextBoxFor(x => x.MYANIMELIST, new { @style = "width:100%; border:1px solid #000000;padding:3px;" })
    </div>
    <div class="form-group">
        <label for="exampleInputName1">Yayın Yılı</label><br />
        @Html.TextBoxFor(x => x.DATE, "{0:yyyy-MM-dd}", new { @type = "date", @style = "width:100%; border:1px solid #000000;padding:3px;" })
    </div>
    <div class="form-group">
        <label for="exampleInputEmail3">Açıklama</label><br />
        @Html.TextAreaFor(x => x.DETAIL, 10, 2, new { @style = "width:100%; border:1px solid #000000;padding:3px;" })
    </div>
    <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
    <a style="color:#ffffff;" class="btn btn-light" href="/LanetlerKralıAdmin/Anime">Vazgeç</a>
}